services:
  app:
    build: .
    container_name: yargi_mcp_backend_app
    restart: always
    ports:
      - "127.0.0.1:8005:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - HOST=0.0.0.0
      - PORT=8000